### ISSUE TITLE
Next Greater Element Using Stack

### ISSUE THREAD

**Issue by dude01-stack** [dude01-stack/DS-Algo-at-1#47]

**Comment by piyush9311** [comment]
Pls assign this issue to me under hacktoberfest 2022.

**Comment by Ishantgarg-web** [comment]
please assign this task to me

**Comment by nkmishra217** [comment]
please assign this to me I would like to do it in java.

**Comment by sanjaysargam** [comment]
Can u plz assign me ?

**Comment by dmdbilal** [comment]
I want to work on this issue in python.

**Comment by sakshik0** [comment]
i want to work on it in c++, for hacktoberfest
